# Generated by Django 2.2.6 on 2020-01-19 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('supported_socket', models.CharField(max_length=400)),
                ('dissipated_tdp', models.IntegerField()),
                ('power', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount_of_memory', models.IntegerField()),
                ('cache_size', models.IntegerField()),
                ('power', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpu_socket', models.CharField(max_length=100)),
                ('graphics_card_socket', models.CharField(max_length=100)),
                ('memory_slot', models.CharField(max_length=100)),
                ('power', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('power', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clock_frequency', models.IntegerField()),
                ('socket', models.CharField(max_length=100)),
                ('cores', models.IntegerField()),
                ('tdp', models.IntegerField()),
                ('memory_type', models.CharField(max_length=100)),
                ('power', models.IntegerField()),
                ('max_memory_volume', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clock_frequency', models.IntegerField()),
                ('memory_type', models.CharField(max_length=100)),
                ('amount_of_memory', models.IntegerField()),
                ('power', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clock_frequency', models.IntegerField()),
                ('video_memory', models.IntegerField()),
                ('socket', models.CharField(max_length=100)),
                ('power', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField()),
                ('case_level', models.IntegerField()),
                ('cooling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='component_parts.Cooling')),
                ('cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='component_parts.Processor')),
                ('hdd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='component_parts.HDD')),
                ('mother_board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='component_parts.MotherBoard')),
                ('power_supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='component_parts.PowerSupply')),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='component_parts.RAM')),
                ('video_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='component_parts.VideoCard')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('case_level', models.IntegerField()),
                ('case_text', models.CharField(max_length=1000)),
                ('cooling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='component_parts.Cooling')),
                ('cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='component_parts.Processor')),
                ('hdd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='component_parts.HDD')),
                ('mother_board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='component_parts.MotherBoard')),
                ('power_supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='component_parts.PowerSupply')),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='component_parts.RAM')),
                ('video_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='component_parts.VideoCard')),
            ],
        ),
    ]
