# Generated by Django 2.2.6 on 2020-01-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_parts', '0002_motherboard_slot_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='slot_count',
            field=models.IntegerField(default=1),
        ),
    ]
