# Generated by Django 2.2.6 on 2020-01-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component_parts', '0003_auto_20200120_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motherboard',
            old_name='memory_slot',
            new_name='interface',
        ),
    ]
