# Generated by Django 2.2.6 on 2020-01-19 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component_parts', '0004_auto_20200120_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motherboard',
            old_name='slot_count',
            new_name='memory_slot_count',
        ),
    ]
