# Generated by Django 2.2.6 on 2020-01-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_parts', '0005_auto_20200120_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdd',
            name='power',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ram',
            name='power',
            field=models.IntegerField(default=0),
        ),
    ]
