# Generated by Django 2.2.6 on 2020-01-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_parts', '0007_auto_20200122_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='tips',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
